using System.Linq;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Components;
using Content.Shared.Atmos.EntitySystems;
using Content.Shared.Temperature;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CryoCapsule.Ui;

[GenerateTypedNameReferences]
public sealed partial class GasMixControl : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SharedAtmosphereSystem _atmosphere;

    public GasMixControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _atmosphere = _entityManager.System<SharedAtmosphereSystem>();
    }

    public void Populate(GasMixEntry? gasMix)
    {
        Pressure.Text = Loc.GetString("gas-analyzer-window-pressure-val-text",
            ("pressure", $"{0.00}"));
        Temperature.Text = Loc.GetString("generic-not-available-shorthand");

        GasMixChart.Clear();
        if (gasMix is not { } mix ||
            mix.Pressure < Atmospherics.GasMinMoles ||
            mix.Gases == null)
        {
            GasMixChart.AddEntry(1, Color.Gray, tooltip: "no gas");
            return;
        }

        Pressure.Text = Loc.GetString("gas-analyzer-window-pressure-val-text",
            ("pressure", $"{mix.Pressure:0.00}"));

        var celsius = TemperatureHelpers.KelvinToCelsius(mix.Temperature);
        Temperature.Text = Loc.GetString("gas-analyzer-window-temperature-val-text",
            ("tempK", $"{mix.Temperature:0.0}"),
            ("tempC", $"{celsius:0.0}"));

        var totalGasAmount = mix.Gases.Sum(gas => gas.Amount);

        foreach (var gasEntry in mix.Gases)
        {
            var gasProto = _atmosphere.GetGas(gasEntry.Gas);
            var percent = gasEntry.Amount / totalGasAmount * 100;
            var localizedName = Loc.GetString(gasProto.Name);
            var tooltip = Loc.GetString("gas-analyzer-window-molarity-percentage-text",
                ("gasName", localizedName),
                ("amount", $"{gasEntry.Amount:0.##}"),
                ("percentage", $"{percent:0.#}"));
            GasMixChart.AddEntry(gasEntry.Amount, gasProto.Color, tooltip: tooltip);
        }
    }
}
