using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Moffstation.CryoCapsule.Ui;

[GenerateTypedNameReferences]
public sealed partial class SolutionInjectorControl : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public Action<int>? OnInjectionPressed;
    public Action? OnEjectPressed;

    public SolutionInjectorControl()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        Inject1.OnPressed += _ => OnInjectionPressed?.Invoke(1);
        Inject5.OnPressed += _ => OnInjectionPressed?.Invoke(5);
        Inject10.OnPressed +=  _ => OnInjectionPressed?.Invoke(10);
        Inject20.OnPressed += _ => OnInjectionPressed?.Invoke(20);
        EjectBeakerButton.OnPressed +=  _ => OnEjectPressed?.Invoke();

    }

    public void Populate(FixedPoint2? capacity, List<ReagentQuantity>? reagents, bool canInject)
    {
        var totalBeakerCapacity = capacity ?? 0;
        var availableQuantity = FixedPoint2.Zero;


        ChemicalsChart.Clear();
        ChemicalsChart.Capacity = (totalBeakerCapacity < 1 ? 50 : (int)totalBeakerCapacity);

        var chartMaxChemsQuantity = ChemicalsChart.Capacity;

        if (reagents == null)
        {
            EjectBeakerButton.Disabled = true;
            Inject1.Disabled = true;
            Inject5.Disabled = true;
            Inject10.Disabled = true;
            Inject20.Disabled = true;
            return;
        }

        foreach (var (reagent, quantity) in reagents)
        {
            availableQuantity += quantity;

            var chemsQuantityOvershoot = FixedPoint2.Max(0, availableQuantity - chartMaxChemsQuantity);
            var chartQuantity = FixedPoint2.Max(0, quantity - chemsQuantityOvershoot);

            var reagentProto = _prototypeManager.Index<ReagentPrototype>(reagent.Prototype);
            ChemicalsChart.SetEntry(
                reagent.Prototype,
                reagentProto.LocalizedName,
                (float)chartQuantity,
                reagentProto.SubstanceColor,
                tooltip: $"{quantity}u {reagentProto.LocalizedName}");
        }

        Inject1.Disabled = (!canInject || availableQuantity < 0.1f);
        Inject5.Disabled = (!canInject || availableQuantity <= 1);
        Inject10.Disabled = (!canInject || availableQuantity <= 5);
        Inject20.Disabled = (!canInject || availableQuantity <= 10);
        EjectBeakerButton.Disabled = false;

    }
}
