using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Robotics;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;

[GenerateTypedNameReferences]
public sealed partial class LawConsoleMain : FancyWindow
{
    public Action<string, SiliconLawset>? OnTransfer;
    public Action<string, SiliconLawset>? OnSave;
    public Action<string>? OnDelete;

    private static readonly string[] names = ["Cartridge", "Standards", "Saved"];

    public LawConsoleMain()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(LawConsoleState state)
    {
        Tabs.RemoveAllChildren();

        // Cartridge
        // todo later.
        var tab0 = new Label
        {
            Text = "TODO LATER !"
        };
        Tabs.AddChild(tab0);
        Tabs.SetTabTitle(0, "Cartridge");

        // Standard
        var tab1 = new LawConsoleTab(state.StandardLawsets, false, false);
        Tabs.AddChild(tab1);
        Tabs.SetTabTitle(1, "Standards");

        // Saved
        var tab2 = new LawConsoleTab(state.SavedLawsets, true, false);
        Tabs.AddChild(tab2);
        Tabs.SetTabTitle(2, "Saved");

    }
}
