using Content.Shared.Actions.Components;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.UI;

[GenerateTypedNameReferences]
public sealed partial class LawConsoleLawDisplay : BoxContainer
{
    public const string StyleClassSiliconLawPositionLabel = "SiliconLawPositionLabel";

    public static readonly string CorruptedString =
        Loc.GetString("ion-storm-law-scrambled-number", ("length", 5));

    private SiliconLaw? _law;

    public event Action<SiliconLaw>? MoveLawUp;
    public event Action<SiliconLaw>? MoveLawDown;
    public event Action<SiliconLaw>? DeleteAction;
    public event Action<SiliconLaw>? AddAction;


    public LawConsoleLawDisplay(bool editable = true)
    {
        RobustXamlLoader.Load(this);

        MoveUp.OnPressed += _ => MoveLawUp?.Invoke(_law!);
        MoveDown.OnPressed += _ => MoveLawDown?.Invoke(_law!);

        LawContent.Editable = editable;

        LawContent.OnTextChanged += _ => _law!.LawString = Rope.Collapse(LawContent.TextRope).Trim();
        LawContent.Placeholder = new Rope.Leaf(Loc.GetString("silicon-law-ui-placeholder"));


        if (editable)
        {
            Delete.OnPressed += _ => DeleteAction?.Invoke(_law!);
        }
        else
        {
            MoveUp.Disabled = true;
            MoveDown.Disabled = true;
            Delete.Text = "Add";
            Delete.OnPressed += _ => AddAction?.Invoke(_law!);
        }
    }

    public void SetLaw(SiliconLaw law)
    {
        _law = law;
        LawContent.TextRope = new Rope.Leaf(Loc.GetString(law.LawString));
        PositionText.Text = law.Order.ToString();
    }
}
