using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;


[GenerateTypedNameReferences]
public sealed partial class LawConsoleLawsetHeader : BoxContainer
{
    public event Action<string>? NameChanged;
    public event Action? LawsetTransfered;
    public event Action? LawsetSaved;
    public event Action? LawsetDeleted;


    public LawConsoleLawsetHeader(string name, bool editable, bool deletable)
    {
        RobustXamlLoader.Load(this);

        NameEdit.Text = name;
        NameEdit.Editable = editable;
        NameEdit.OnTextChanged += newText => NameChanged?.Invoke(newText.Text);

        TransferButton.OnPressed += _ => LawsetTransfered?.Invoke();

        DeleteButton.Disabled = !deletable;
        DeleteButton.OnPressed += _ => LawsetDeleted?.Invoke();

        SaveButton.Disabled = !editable;
        SaveButton.OnPressed += _ =>  LawsetSaved?.Invoke();
    }
}
