using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;


// TODO : issue that the ScrollContainer doesn't seem to actually... be here ?

[GenerateTypedNameReferences]
public sealed partial class LawConsoleTab : BoxContainer
{
    public LawConsoleTab(Dictionary<string, SiliconLawset>? lawsets, bool editable, bool deletable)
    {
        RobustXamlLoader.Load(this);

        if (lawsets != null)
        {
            DisplayLawsetList(lawsets);
            DisplayNoLawset();
        }
        else
        {
            DisplayEmpty();
        }

    }

    private void DisplayLawsetList(Dictionary<string, SiliconLawset> lawsets)
    {
        LawsetButtons.RemoveAllChildren();

        var group = new ButtonGroup();
        foreach (var (name, lawset) in lawsets)
        {
            var button = new Button
            {
                Text = name,
                Group = group,
            };
            button.OnPressed += _ => DisplayLawset(name, lawset);
            LawsetButtons.AddChild(button);
        }
    }

    private void DisplayLawset(string name, SiliconLawset lawset)
    {
        // header
        LawsetContainer.RemoveChild(0);
        var header = new LawConsoleLawsetHeader(name, false, false);
        LawsetContainer.AddChild(header);
        header.SetPositionFirst();

        // laws
        LawsContainer.RemoveAllChildren();
        foreach (var law in lawset.Laws)
        {
            var control = new LawConsoleLawDisplay(false);
            control.SetLaw(law);

            LawsetContainer.AddChild(control);
        }
    }

    private void DisplayNoLawset()
    {
        LawsetContainer.RemoveChild(0);
        var header = new LawConsoleLawsetHeader(string.Empty, false, false);
        LawsetContainer.AddChild(header);
        header.SetPositionFirst();

        LawsContainer.RemoveAllChildren();
        var control = new Label
        {
            Text = "No lawset selected",
        };
        LawsContainer.AddChild(control);
    }

    private void DisplayEmpty()
    {

    }
}
