using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Robotics;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;

[GenerateTypedNameReferences]
public sealed partial class LawConsoleWindow : FancyWindow
{


    public Action<string, SiliconLawset>? OnTransfer;
    public Action<string, SiliconLawset>? OnSave;
    public Action<string>? OnDelete;

    public LawConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        // do that on the displayed stuff maybe ?...
        //TransferButton.OnPressed += OnTransfer?.Invoke();
        //SaveButton.OnPressed += OnSave?.Invoke();
        //DeleteButton.OnPressed += OnDelete?.Invoke();
    }

    public void UpdateState(LawConsoleState state)
    {
        DisplayLawsetList(state.StandardLawsets, state.SavedLawsets);

        if (state.IsCartridgeInserted)
            DisplayLawset(state.CartridgeName, state.CartridgeLawset);
        else
            DisplayNoCartridge();
    }

    private void DisplayLawsetList(Dictionary<string, SiliconLawset> standardLawsets, Dictionary<string, SiliconLawset> savedLawsets)
    {
        LawsetsContainer.RemoveAllChildren();
        foreach (var (name, lawset) in standardLawsets)
        {
            var button = new Button
            {
                Text = name,
            };
            button.OnPressed += _ => DisplayLawset(name, lawset);
            LawsContainer.AddChild(button);
        }

        foreach (var (name, lawset) in savedLawsets)
        {
            var button = new Button
            {
                Text = name,
            };
            button.OnPressed += _ => DisplayLawset(name, lawset);
            LawsContainer.AddChild(button);
        }
    }

    private void DisplayLawset(string name, SiliconLawset lawset)
    {
        NameEdit.Text = name;
        NameEdit.Editable = false;

        LawsContainer.RemoveAllChildren();
        foreach (var law in lawset.Laws)
        {
            var control = new LawConsoleLawDisplay(false);
            control.SetLaw(law);

            LawsContainer.AddChild(control);
        }
    }


    private void DisplayNoCartridge()
    {
        NameEdit.Text = string.Empty;
        NameEdit.Editable = false;

        LawsContainer.RemoveAllChildren();
        var label = new Label
        {
            Text = "{Loc law_console_no_cartridge}",
        };
        LawsContainer.AddChild(label);
    }


    private void MoveCartridgeLawUp()
    {

    }

    private void MoveCartridgeLawDown()
    {

    }

    private void AddCartridgeLaw()
    {

    }

    private void DeleteCartridgeLaw()
    {

    }


    private void OrderCartridgeLaws()
    {

    }
}
