using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Robotics;
using Content.Shared.FixedPoint;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;

[GenerateTypedNameReferences]
public sealed partial class LawConsoleWindow : FancyWindow
{
    private LawConsoleState? currentState;

    public Action<string, SiliconLawset>? OnTransfer;
    public Action<string, SiliconLawset>? OnSave;
    public Action<string>? OnDelete;

    public LawConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        NewLawButton.OnPressed += _ => AddCartridgeLaw();
    }

    public void UpdateState(LawConsoleState state)
    {
        currentState = state;

        DisplayLawsetList(state.StandardLawsets, state.SavedLawsets);

        if (state.IsCartridgeInserted)
            DisplayLawset(state.CartridgeName, state.CartridgeLawset, true);
        else
            DisplayNoCartridge();
    }

    private void DisplayLawsetList(Dictionary<string, SiliconLawset> standardLawsets, Dictionary<string, SiliconLawset> savedLawsets)
    {
        LawsetsContainer.RemoveAllChildren();

        var cartridgeButton = new Button
        {
            Text = "CARTRIDGE",
        };
        cartridgeButton.OnPressed += _ =>
        {
            if (currentState is { IsCartridgeInserted: true })
                DisplayLawset(currentState.CartridgeName, currentState.CartridgeLawset, true);
            else
                DisplayNoCartridge();
        };

        LawsetsContainer.AddChild(cartridgeButton);

        foreach (var (name, lawset) in standardLawsets)
        {
            var button = new Button
            {
                Text = name,
            };
            button.OnPressed += _ => DisplayLawset(name, lawset, false);
            LawsetsContainer.AddChild(button);
        }

        foreach (var (name, lawset) in savedLawsets)
        {
            var button = new Button
            {
                Text = name,
            };
            button.OnPressed += _ => DisplayLawset(name, lawset, false);
            LawsetsContainer.AddChild(button);
        }
    }

    private void DisplayLawset(string name, SiliconLawset lawset, bool editable)
    {
        Test.RemoveChild(0); // remove previous header

        var header = new LawConsoleLawsetHeader(name, editable, false);
        header.LawsetTransfered += () => OnTransfer?.Invoke(name, lawset);
        header.LawsetSaved += () => OnSave?.Invoke(name, lawset);
        header.LawsetDeleted += () => OnDelete?.Invoke(name);

        Test.AddChild(header);
        header.SetPositionInParent(0);


        LawsContainer.RemoveAllChildren();
        foreach (var law in lawset.Laws)
        {
            var control = new LawConsoleLawDisplay(editable);
            control.SetLaw(law);
            control.MoveLawUp += _ => MoveCartridgeLawUp(law);
            control.MoveLawDown += _ => MoveCartridgeLawDown(law);
            control.DeleteLaw += _ => DeleteCartridgeLaw(law);

            LawsContainer.AddChild(control);
        }
    }


    private void DisplayNoCartridge()
    {
        NameEdit.Text = string.Empty;
        NameEdit.Editable = false;

        LawsContainer.RemoveAllChildren();
        var label = new Label
        {
            Text = Loc.GetString("law-console-no-cartridge"),
            VAlign = Label.VAlignMode.Center,
            HorizontalAlignment = Label.HAlignment.Center,
        };
        LawsContainer.AddChild(label);
    }


    private void MoveCartridgeLawUp(SiliconLaw law)
    {
        if (currentState == null)
            return;

        if (currentState.CartridgeLawset.Laws.Count == 0)
            return;

        var index = currentState.CartridgeLawset.Laws.IndexOf(law);
        if (index == 0 || index == -1)
            return;

        (currentState.CartridgeLawset.Laws[index - 1], currentState.CartridgeLawset.Laws[index]) =
            (currentState.CartridgeLawset.Laws[index], currentState.CartridgeLawset.Laws[index - 1]);

        OrderCartridgeLaws();
        DisplayLawset(currentState.CartridgeName, currentState.CartridgeLawset, true);
    }

    private void MoveCartridgeLawDown(SiliconLaw law)
    {
        if (currentState == null)
            return;

        if (currentState.CartridgeLawset.Laws.Count == 0)
            return;

        var index = currentState.CartridgeLawset.Laws.IndexOf(law);
        if (index == currentState.CartridgeLawset.Laws.Count - 1 || index == -1)
            return;

        (currentState.CartridgeLawset.Laws[index + 1], currentState.CartridgeLawset.Laws[index]) =
            (currentState.CartridgeLawset.Laws[index], currentState.CartridgeLawset.Laws[index + 1]);

        OrderCartridgeLaws();
        DisplayLawset(currentState.CartridgeName, currentState.CartridgeLawset, true);
    }

    private void AddCartridgeLaw(SiliconLaw? law = null)
    {
        if (currentState is not { IsCartridgeInserted: true })
            return;

        if (law != null)
            currentState.CartridgeLawset.Laws.Add(law);
        else
            currentState.CartridgeLawset.Laws.Add(new SiliconLaw());

        OrderCartridgeLaws();
        DisplayLawset(currentState.CartridgeName, currentState.CartridgeLawset, true);
    }

    private void DeleteCartridgeLaw(SiliconLaw law)
    {
        if (currentState == null)
            return;

        if (currentState.CartridgeLawset.Laws.Count == 0)
            return;

        var index = currentState.CartridgeLawset.Laws.IndexOf(law);
        if (index == -1)
            return;

        currentState.CartridgeLawset.Laws.RemoveAt(index);

        OrderCartridgeLaws();
        DisplayLawset(currentState.CartridgeName, currentState.CartridgeLawset, true);
    }


    private void OrderCartridgeLaws()
    {
        if (currentState == null)
            return;

        if (currentState.CartridgeLawset.Laws.Count == 0)
            return;

        if (currentState.CartridgeLawset.Laws[0].Order != FixedPoint2.Zero)
            currentState.CartridgeLawset.Laws[0].Order = 1;

        for (int i = 1; i < currentState.CartridgeLawset.Laws.Count; i++)
        {
            currentState.CartridgeLawset.Laws[i].Order = currentState.CartridgeLawset.Laws[i - 1].Order + 1;
        }
    }
}
