using Content.Shared.FixedPoint;
using Content.Shared.Power;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;


[GenerateTypedNameReferences]
public sealed partial class LCLawset : BoxContainer
{
    public Action<string, SiliconLawset>? OnTransfer;
    public Action<string, SiliconLawset>? OnSave;
    public Action<string>? OnDelete;

    private bool _isCartridge;
    SiliconLawset _siliconLawset;

    public LCLawset(string name, SiliconLawset lawset, bool isCartridge, bool deletable)
    {
        RobustXamlLoader.Load(this);

        _siliconLawset = lawset.Clone();
        _isCartridge = isCartridge;

        NameEdit.Text = name;
        NameEdit.Editable = isCartridge;

        SaveButton.Disabled = !isCartridge;
        SaveButton.OnPressed += _ => SaveLawset();

        DeleteButton.Disabled = !deletable;
        DeleteButton.OnPressed += _ => DeleteLawset();

        TransferButton.OnPressed += _ => TransferLawset();

        foreach (var law in _siliconLawset.Laws)
        {
            var control = new LCLaw(law, isCartridge);

            control.OnDelete += _ => DeleteLaw(law);
            control.OnMoveUp += _ => MoveLawUp(law);
            control.OnMoveDown += _ => MoveLawDown(law);
            control.OnModified += (_law, _text) => ChangeLaw(_law, _text);

            LawControls.AddChild(control);
        }

        if (!isCartridge)
            return;

        var newLawButton = new Button
        {
            Text = "Add Law",
            HorizontalExpand = true,
        };
        newLawButton.OnPressed += _ => AddNewLaw();

        LawControls.AddChild(newLawButton);
    }

    #region Laws Functions
    public void MoveLawUp(SiliconLaw law)
    {
        if (_siliconLawset.Laws.Count == 0)
            return;

        var index =  _siliconLawset.Laws.IndexOf(law);

        if (index == 0 || index == -1)
            return;

        (_siliconLawset.Laws[index - 1], _siliconLawset.Laws[index]) =
            (_siliconLawset.Laws[index], _siliconLawset.Laws[index - 1]);

        OrderLaws();
        Refresh();
    }

    public void MoveLawDown(SiliconLaw law)
    {
        if (_siliconLawset.Laws.Count == 0)
            return;

        var index =  _siliconLawset.Laws.IndexOf(law);

        if (index == _siliconLawset.Laws.Count - 1 || index == -1)
            return;

        (_siliconLawset.Laws[index + 1], _siliconLawset.Laws[index]) =
            (_siliconLawset.Laws[index], _siliconLawset.Laws[index + 1]);

        OrderLaws();
        Refresh();
    }

    public void AddNewLaw()
    {
        _siliconLawset.Laws.Add(new SiliconLaw());

        OrderLaws();
        Refresh();
    }

    public void DeleteLaw(SiliconLaw law)
    {
        if (_siliconLawset.Laws.Count == 0)
            return;

        var index = _siliconLawset.Laws.IndexOf(law);
        if (index == -1)
            return;

        _siliconLawset.Laws.RemoveAt(index);

        OrderLaws();
        Refresh();
    }

    public void ChangeLaw(SiliconLaw law, string text)
    {
        if (_siliconLawset.Laws.Count == 0)
            return;

        var index = _siliconLawset.Laws.IndexOf(law);
        if (index == -1)
            return;

        _siliconLawset.Laws[index].LawString = text;
    }

    public void OrderLaws()
    {
        if (_siliconLawset.Laws.Count == 0)
            return;

        if (_siliconLawset.Laws[0].Order != FixedPoint2.Zero)
            _siliconLawset.Laws[0].Order = 1;

        for (int i = 1; i < _siliconLawset.Laws.Count; i++)
        {
            _siliconLawset.Laws[i].Order = _siliconLawset.Laws[i - 1].Order + 1;
        }
    }

    public void Refresh()
    {
        LawControls.RemoveAllChildren();

        foreach (var law in _siliconLawset.Laws)
        {
            var control = new LCLaw(law, _isCartridge);
            control.OnDelete += _ => DeleteLaw(law);
            control.OnMoveUp += _ => MoveLawUp(law);
            control.OnMoveDown += _ => MoveLawDown(law);
            control.OnModified += (_law, _text) => ChangeLaw(_law, _text);

            LawControls.AddChild(control);
        }

        if (!_isCartridge)
            return;

        var newLawButton = new Button
        {
            Text = "Add Law",
            HorizontalExpand = true,
        };
        newLawButton.OnPressed += _ => AddNewLaw();

        LawControls.AddChild(newLawButton);
    }
    #endregion

    #region Lawset Functions
    public void TransferLawset()
    {
        OnTransfer?.Invoke(NameEdit.Text, _siliconLawset);
    }

    public void SaveLawset()
    {
        OnSave?.Invoke(NameEdit.Text, _siliconLawset);
    }

    public void DeleteLawset()
    {
        OnDelete?.Invoke(NameEdit.Text);
    }
    #endregion
}
