using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.Robotics.UI;

[GenerateTypedNameReferences]

public sealed partial class LCLaw : BoxContainer
{
    public Action<SiliconLaw>? OnDelete;
    public Action<SiliconLaw>? OnMoveUp;
    public Action<SiliconLaw>? OnMoveDown;
    public Action<SiliconLaw, string>? OnModified;

    public LCLaw(SiliconLaw siliconLaw, bool editable)
    {
        RobustXamlLoader.Load(this);

        PositionText.Text = siliconLaw.Order.ToString();

        LawContent.TextRope = new Rope.Leaf(Loc.GetString(siliconLaw.LawString));
        LawContent.Editable = editable;
        LawContent.OnTextChanged += _ => OnModified?.Invoke(siliconLaw, Rope.Collapse(LawContent.TextRope).Trim());

        MoveUp.Disabled = !editable;
        MoveUp.OnPressed += _ => OnMoveUp?.Invoke(siliconLaw);

        MoveDown.Disabled = !editable;
        MoveDown.OnPressed += _ => OnMoveDown?.Invoke(siliconLaw);

        ActionButton.Disabled = !editable;
        ActionButton.OnPressed += _ => OnDelete?.Invoke(siliconLaw);
    }
}
