using Content.Client._Moffstation.Robotics.UI;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;

[GenerateTypedNameReferences]
public sealed partial class LCTab : BoxContainer
{
    public Action<string, SiliconLawset>? OnTransfer;
    public Action<string, SiliconLawset>? OnSave;
    public Action<string>? OnDelete;

    // maybe add an argument to pre-select ? if none then select -1 ?...
    public LCTab(Dictionary<string, SiliconLawset> lawsets, bool is_cartridge, bool is_deletable)
    {
        RobustXamlLoader.Load(this);

        var group = new ButtonGroup();
        foreach (var (name, lawset) in lawsets)
        {
            var button = new Button
            {
                Text = name,
                Group = group,
            };
            button.OnPressed += _ => DisplayLawset(name, lawset, is_cartridge, is_deletable);
            LawsetButtons.AddChild(button);
        }

        DisplayNoLawset();
    }

    public static Control Empty(string message)
    {
        return new Label { Text = message, };
    }

    public void DisplayLawset(string name, SiliconLawset lawset, bool is_cartridge, bool is_deletable)
    {
        LawsetControl.RemoveAllChildren();

        var lawsetPanel = new LCLawset(name, lawset, is_cartridge, is_deletable);
        lawsetPanel.OnTransfer += (name, lawset) => OnTransfer?.Invoke(name, lawset);
        lawsetPanel.OnSave += (name, lawset) => OnSave?.Invoke(name, lawset);
        lawsetPanel.OnDelete += (name) => OnDelete?.Invoke(name);


        LawsetControl.AddChild(lawsetPanel);
    }

    public void DisplayNoLawset()
    {
        LawsetControl.RemoveAllChildren();
        var control = new Label
        {
            Text = "No Lawset Selected",
        };
        LawsetControl.AddChild(control);
    }
}
