using Content.Client.Administration.UI.Tabs.ObjectsTab;
using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.Robotics;
using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.Robotics.UI;

[GenerateTypedNameReferences]
public sealed partial class LCWindow : FancyWindow
{
    public Action<string, SiliconLawset>? OnSave;
    public Action<string, SiliconLawset>? OnTransfer;
    public Action<string>? OnDelete;

    public LCWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(LawConsoleState state)
    {
        Tabs.RemoveAllChildren();

        // cartridge
        var cartridge = state.IsCartridgeInserted
            ? FullTab(new Dictionary<string, SiliconLawset> { {state.CartridgeName, state.CartridgeLawset} }, true, false)
            : EmptyTab("No Cartridge");

        Tabs.AddChild(cartridge);
        Tabs.SetTabTitle(0, "Cartridge");

        // standards
        var standard = state.StandardLawsets.Count == 0
            ? EmptyTab("No Standard")
            : FullTab(state.StandardLawsets, false, false);
        Tabs.AddChild(standard);
        Tabs.SetTabTitle(1, "Standard");

        // saved
        var saved = state.SavedLawsets.Count == 0
            ? EmptyTab("No Saved")
            : FullTab(state.SavedLawsets, false, true);
        Tabs.AddChild(saved);
        Tabs.SetTabTitle(2, "Saved");
    }

    private LCTab FullTab(Dictionary<string, SiliconLawset> lawsets, bool is_cartridge, bool is_deletable)
    {
        var tab = new LCTab(lawsets, is_cartridge, is_deletable);
        tab.OnSave += (name, lawset) => OnSave?.Invoke(name, lawset);
        tab.OnTransfer += (name, lawset) => OnTransfer?.Invoke(name, lawset);
        tab.OnDelete += (name) => OnDelete?.Invoke(name);

        return tab;
    }

    private Control EmptyTab(string message)
    {
        return LCTab.Empty(message);
    }
}
