using Content.Client.UserInterface.Controls;
using Content.Shared._Moffstation.CryoCapsule.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CryoCapsule;

[GenerateTypedNameReferences]
public sealed partial class CryoLifeSupportWindow : FancyWindow
{
    public Action<int>? OnInjectionPressed;
    public Action? OnRevivePatientPressed;
    public Action? OnEjectPatientPressed;
    public Action? OnEjectBeakerPressed;

    public CryoLifeSupportWindow()
    {
        RobustXamlLoader.Load(this);

        SolutionInjectorControl.OnInjectionPressed += amount => OnInjectionPressed?.Invoke(amount);
        SolutionInjectorControl.OnEjectPressed += () => OnEjectBeakerPressed?.Invoke();
        EjectPatientButton.OnPressed += _ => OnEjectPatientPressed?.Invoke();
        RevivePatientButton.OnPressed += _ => OnRevivePatientPressed?.Invoke();
    }

    public void SetState(CryoLifeSupportBuiMessage message)
    {
        var havePatient = message.Health.TargetEntity != null;

        GasMixControl.Populate(message.GasMix);
        SolutionInjectorControl.Populate(message.BeakerCapacity, message.Beaker, havePatient);

        EjectPatientButton.Disabled = !havePatient;
        RevivePatientButton.Disabled = !havePatient;

        if (!havePatient)
        {
            PatientSection.Visible = false;
            return;
        }

        PatientSection.Visible = true;
        PatientHealthControl.Populate(message.Health);
    }
}
